const mongoose = require('mongoose')
const coinSchema = new mongoose.Schema({
    name: {type: String, required: true},
    denomination: {type: String, required: false},
    year: {type: Number, required: true},
    worth: {type: Number, required: false},
    tags: {type: String, required: false},
})

const Coin = mongoose.model("Coin", coinSchema);
module.exports = Coin;

const coins = [
    {
        name: "Eisenhour Dollar", 
        denomination: "One Dollar",
        year: 1974,
        worth: 2,
        tags: ["nothing unique"],
    },
    {
        name: "Eisenhour Bicentennial Dollar", 
        denomination: "One Dollar",
        year: 1976,
        worth: 2,
        tags: ["discolored", "copper=like coloring"],
    },   
    {
        name: "Eisenhour Dollar", 
        denomination: "One Dollar",
        year: 1978,
        worth: 2,
        tags: ["good conditions"],
    }, 
    {
        name: "Eisenhour Dollar", 
        denomination: "One Dollar",
        year: 1974,
        worth: 2,
        tags: ["very defined"],
    },
    {
        name: "Eisenhour Dollar", 
        denomination: "One Dollar",
        year: 1974,
        worth: 2,
        tags: ["Variety 2"],
    },
    {
        name: "Eisenhour Bicentennial Dollar", 
        denomination: "One Dollar",
        year: 1976,
        worth: 1,
        tags: ["Alaska flag painting"],
    },
    {
        name: "Indian Head", 
        denomination: "Penny",
        year: 1903,
        worth: 3,
        tags: ["faded", "set"],
    },
    {
        name: "Indian Head", 
        denomination: "Penny",
        year: 1900,
        worth: 2,
        tags: ["faded"],
    },
    {
        name: "Indian Head", 
        denomination: "Penny",
        year: 1902,
        worth: 2,
        tags: ["faded"],
    },
    {
        name: "Indian Head", 
        denomination: "Penny",
        year: 1903,
        worth: 2,
        tags: ["faded"],
    },
    {
        name: "Indian Head", 
        denomination: "Penny",
        year: 1905,
        worth: 2,
        tags: ["faded"],
    },
    {
        name: "Indian Head", 
        denomination: "Penny",
        year: 1901,
        worth: 2,
        tags: ["more defined"],
    },
    {
        name: "Lincoln", 
        denomination: "Penny",
        year: 1929,
        worth: .2,
        tags: ["more defined", "set"],
    },
    {
        name: "Liberty Head", 
        denomination: "Nickle",
        year: 1901,
        worth: 2,
        tags: ["very faded", "G4 or Lower"],
    },
    {
        name: "Liberty Head", 
        denomination: "Nickle",
        year: 1907,
        worth: 2,
        tags: ["very faded"],
    },
    {
        name: "Liberty Head", 
        denomination: "Nickle",
        year: 1912,
        worth: 2,
        tags: ["G4 or Lower"],
    },
    {
        name: "Liberty Head", 
        denomination: "Nickle",
        year: 1903,
        worth: 2,
        tags: ["G4 or Lower"],
    },
    {
        name: "Wartime Jefferson", 
        denomination: "Nickle",
        year: 1943,
        worth: 2.5,
        tags: ["G4 or Lower", "set"],
    },
    {
        name: "Buffalo Head", 
        denomination: "Nickle",
        year: 1930,
        worth: 1.25,
        tags: ["P", "set"],
    },
    {
        name: "Silver Mercury", 
        denomination: "Dime",
        year: 1944,
        worth: 2.75,
        tags: ["W", "set"],
    },
    {
        name: "Bicentennial Washington", 
        denomination: "Quarter",
        year: 1976,
        worth: 1.25,
        tags: ["none", "set"],
    },
    {
        name: "JFK Bicentennial", 
        denomination: "Half Dollar",
        year: 1976,
        worth: 3,
        tags: ["very clear", "set"],
    },
]
